//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public System.Guid notificationId { get; set; }
        public Nullable<System.Guid> commandeId { get; set; }
        public Nullable<bool> statut { get; set; }
        public Nullable<System.Guid> fromId { get; set; }
        public Nullable<System.Guid> toId { get; set; }
        public Nullable<System.DateTime> datenotif { get; set; }
        public string message { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
        public virtual UTILISATEUR FROMUSER { get; set; }
        public virtual UTILISATEUR TOUSER { get; set; }
    }
}
