//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int idUserRole { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<System.Guid> idUser { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
