//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURE()
        {
            this.COMMANDEs = new HashSet<COMMANDE>();
        }
    
        public System.Guid factureId { get; set; }
        public int factureNumero { get; set; }
        public System.DateTime dateEmission { get; set; }
        public System.DateTime dateDebut { get; set; }
        public System.DateTime dateFin { get; set; }
        public string montant { get; set; }
        public Nullable<bool> etat { get; set; }
        public Nullable<System.Guid> redacteurId { get; set; }
        public Nullable<System.Guid> createurId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE> COMMANDEs { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual UTILISATEUR UTILISATEUR1 { get; set; }
    }
}
