//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELE()
        {
            this.TEMPLATEs = new HashSet<TEMPLATE>();
        }
    
        public System.Guid modeleId { get; set; }
        public string logoUrl { get; set; }
        public string menu1_titre { get; set; }
        public string menu2_titre { get; set; }
        public string menu3_titre { get; set; }
        public string menu4_titre { get; set; }
        public string menu1_paragraphe1_titre { get; set; }
        public string menu1_paragraphe2_titre { get; set; }
        public string menu1_contenu1 { get; set; }
        public string menu1_contenu2 { get; set; }
        public string menu1_paragraphe1_photoUrl { get; set; }
        public string menu1_paragraphe2_photoUrl { get; set; }
        public string menu2_paragraphe1_titre { get; set; }
        public string menu2_paragraphe2_titre { get; set; }
        public string menu2_contenu1 { get; set; }
        public string menu2_contenu2 { get; set; }
        public string menu2_paragraphe1_photoUrl { get; set; }
        public string menu2_paragraphe2_photoUrl { get; set; }
        public string menu3_paragraphe1_titre { get; set; }
        public string menu3_paragraphe2_titre { get; set; }
        public string menu3_contenu1 { get; set; }
        public string menu3_contenu2 { get; set; }
        public string menu3_paragraphe1_photoUrl { get; set; }
        public string menu3_paragraphe2_photoUrl { get; set; }
        public string menu4_paragraphe1_titre { get; set; }
        public string menu4_paragraphe2_titre { get; set; }
        public string menu4_contenu1 { get; set; }
        public string menu4_contenu2 { get; set; }
        public string menu4_paragraphe1_photoUrl { get; set; }
        public string menu4_paragraphe2_photoUrl { get; set; }
        public string photoALaUneUrl { get; set; }
        public string site_url { get; set; }
        public string menu1_meta_description { get; set; }
        public string menu2_meta_description { get; set; }
        public string menu3_meta_description { get; set; }
        public string menu4_meta_description { get; set; }
        public string menu1_p1_alt { get; set; }
        public string menu1_p2_alt { get; set; }
        public string menu2_p1_alt { get; set; }
        public string menu2_p2_alt { get; set; }
        public string menu3_p1_alt { get; set; }
        public string menu3_p2_alt { get; set; }
        public string menu4_p1_alt { get; set; }
        public string menu4_p2_alt { get; set; }
        public string favicone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMPLATE> TEMPLATEs { get; set; }
    }
}
