//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class redactapplicationEntities : DbContext
    {
        public redactapplicationEntities()
            : base("name=redactapplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMANDE> COMMANDEs { get; set; }
        public virtual DbSet<COMMANDE_TYPE> COMMANDE_TYPE { get; set; }
        public virtual DbSet<FACTURE> FACTUREs { get; set; }
        public virtual DbSet<MODELE> MODELEs { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONs { get; set; }
        public virtual DbSet<PROJET> PROJETS { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<STATUT_COMMANDE> STATUT_COMMANDE { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATEs { get; set; }
        public virtual DbSet<THEME> THEMES { get; set; }
        public virtual DbSet<USER_THEME> USER_THEME { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UTILISATEUR> UTILISATEURs { get; set; }
        public virtual DbSet<REDACT_THEME> REDACT_THEME { get; set; }
        public virtual DbSet<TAG> TAGS { get; set; }
        public virtual DbSet<SITE> SITES { get; set; }
    }
}
