//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE
    {
        public System.Guid templateId { get; set; }
        public Nullable<System.Guid> projetId { get; set; }
        public Nullable<System.Guid> themeId { get; set; }
        public string url { get; set; }
        public string ftpUser { get; set; }
        public string ftpPassword { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public string html { get; set; }
        public Nullable<System.Guid> modeleId { get; set; }
        public string ip { get; set; }
    
        public virtual MODELE MODELE { get; set; }
        public virtual PROJET PROJET { get; set; }
        public virtual THEME THEME { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
