//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedactApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_THEME
    {
        public System.Guid userThemeId { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public Nullable<System.Guid> themeId { get; set; }
    
        public virtual THEME THEME { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
